name: Docker Build and Push

on:
  push:
    branches:
      - production
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2.0.1
        id: login-ecr
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3.0.0
      - run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
      - name: Set up meta data
        id: meta
        uses: docker/metadata-action@v5.3.0
        with:
          images: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
          tags: |
            value=latest
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: python-test
      - name: docker build and push ECR
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # Actionsで使用するCacheの設定
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
